### PR TITLE
api spec for uctrunking hosted feature setting

### PR DESCRIPTION
**Pull request by xxlaykxx**
POST GET PUT /accounts/{accountId}/products/uctrunking/features/hosted/settings

Снимок экрана 2022-09-24 в 12 36 47
Снимок экрана 2022-09-24 в 12 37 04
Снимок экрана 2022-09-24 в 12 36 55

### CODE REVIEW

**Review by ajrice6713 — APPROVED** [review]

**Review by mrmeyers99 — APPROVED** [review]
Is there a better tag you could use? We're trying to get rid of /accounts

**Comment by xxlaykxx** [comment]
@mrmeyers99 we have several GET endpoints for different product settings - I could add one tag for all of them like "Product Settings", What do you think?

**Comment by mrmeyers99** [comment]
> @mrmeyers99 we have several GET endpoints for different product settings - I could add one tag for all of them like "Product Settings", What do you think?

That makes sense to me.  I'm happy for that to be a separate PR though.

**Comment by xxlaykxx** [comment]
Ok, then let's merge this one and I will creat another pr with new tag

**Pull request merged**
