### PR TITLE
RemoveImportedTnOrdersReportResponse example for RemoveImportedTnOrders endpoints

### PR DESCRIPTION
**Pull request by safronenko23**
RemoveImportedTnOrdersReportResponse examples

**⚠️Please do not make any changes to spec files in this repository!⚠️**

**All spec changes should be done in the [api-specs](https://github.com/Bandwidth/api-specs) repository.**

**Please follow the [Guide](https://bandwidth-jira.atlassian.net/wiki/spaces/DX/pages/4098359409/How+to+Update+API+Specifications+and+Contribute+to+Developer+Documentation) for contributing to our developer documentation.**

### CODE REVIEW

**Comment by ajrice6713** [comment]
@safronenko23 do you have an example of a request i could send the live API to mimic this and check the response? 

If this is correct, we might need to note this for the SDKs

**Comment by safronenko23** [comment]
@ajrice6713 Did you have success? 
About SKD, not sure what I need to do...

**Comment by ajrice6713** [comment]
@safronenko23 no need for you to do anything to SDK (unless you feel passionate about updating a 7 year old Java client) 

I was able to reproduce and will take the steps to get the SDK Updated

**Review by ajrice6713 — APPROVED** [review]

**Comment by safronenko23** [comment]
@ajrice6713 any move on this?

**Review by mrmeyers99 — APPROVED** [review]

**Pull request merged**
